# BOARD_TAG    = mega
# BOARD_SUB    = atmega2560
# MONITOR_PORT = /dev/ttyACM0
BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyUSB1
ARDUINO_LIBS =  DHT-sensor-library-master Adafruit_BMP085_Unified-master Wire Adafruit_Sensor-master RF24-master SPI
ARDMK_DIR    = /home/aardvark/external_src/Arduino-Makefile/
ARDUINO_DIR  = /home/aardvark/arduino-1.8.0
AVRDUDE      = /usr/bin/avrdude

include ../Arduino.mk
