BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM0
ARDMK_DIR    = /home/aardvark/src/Arduino-Makefile/
ARDUINO_DIR  = /home/aardvark/arduino-1.6.8
ARDUINO_LIBS = RFReceiver-master DHT-sensor-library-master PinChangeInterruptHandler-master Adafruit_Sensor-master
AVRDUDE      = /usr/bin/avrdude

include ../Arduino.mk
