# BOARD_TAG    = mega
# BOARD_SUB    = atmega2560
# MONITOR_PORT = /dev/ttyACM0
BOARD_TAG    = uno
ARDUINO_LIBS = RFReceiver-master DHT-sensor-library-master PinChangeInterruptHandler-master Adafruit_Sensor-master
MONITOR_PORT = /dev/ttyUSB1
ARDMK_DIR    = /home/aardvark/external_src/Arduino-Makefile/
ARDUINO_DIR  = /home/aardvark/arduino-1.8.0
AVRDUDE      = /usr/bin/avrdude

include ../Arduino.mk
