BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyUSB0
ARDUINO_LIBS = RFTransmitter-master DHT-sensor-library-master Adafruit_BMP085_Unified-master Wire Adafruit_Sensor-master
ARDMK_DIR    = /home/aardvark/src/Arduino-Makefile/
ARDUINO_DIR  = /home/aardvark/arduino-1.6.8
AVRDUDE      = /usr/bin/avrdude

include ../Arduino.mk
